### ISSUE TITLE
Convert errors with 'Multiple node elments can't be created'

### ISSUE THREAD

**Issue by tomaustin700** [baynezy/Html2Markdown#81]
# Report issue
Hi,
When running Convert on a string I am getting a unhandled exception stating 'Multiple node elments can't be created'. I have attached a sample solution demonstrating this issue. 

## Expected behavior
Convert does not crash.

## Actual Behaviour
Throws unhandled System.Exception: 'Multiple node elments can't be created'

## Steps to reproduce the problem
To duplicate just run the solution and it will crash when converting.

[Html2MarkdownBugTest.zip](https://github.com/baynezy/Html2Markdown/files/1818666/Html2MarkdownBugTest.zip)

**Comment by baynezy** [comment]
@tomaustin700 - I have added a test to show this is not actually a bug in this library. [f417907](https://github.com/baynezy/Html2Markdown/commit/f41790727e8c136d9987d5099cd01429459d8065)

You can see the [test results](https://ci.appveyor.com/project/baynezy/html2markdown/build/3.2.1.343) to prove that.

The error in your attached project occurs in [HtmlAgilityPack](http://html-agility-pack.net/). I believe this is because you have incorrectly used the latest version whereas Html2Markdown depends on [1.5.0](https://www.nuget.org/packages/Html2Markdown). NuGet should have installed that version when you installed Html2Markdown.

This project will never upgrade HtmlAgilityPack because of zzzprojects/html-agility-pack/#74 instead we will upgrade to [AngleSharp](https://github.com/AngleSharp/AngleSharp) in the next major version when #68 is completed.

**Comment by tomaustin700** [comment]
@baynezy Changing HtmlAgilityPack to 1.5.0 does seem to resolve this. Thanks.

**Comment by mitchavines** [comment]
Hello,

I'm getting this error on anything I try to convert though I have tried both HtmlAgilityPack 1.5.0 and 1.5.5... I'm clearly missing a beat, help please?

**Comment by baynezy** [comment]
@mitchavines do you have reproduceable case you can link to?

**Comment by mitchavines** [comment]
Apologies, should have done so in the first place.

I'll reproduce (or sort myself out) in a sample project and check back...

Thanks!

**Comment by Kellen-Stuart** [comment]
> @tomaustin700 - I have added a test to show this is not actually a bug in this library. [f417907](https://github.com/baynezy/Html2Markdown/commit/f41790727e8c136d9987d5099cd01429459d8065)
> 
> You can see the [test results](https://ci.appveyor.com/project/baynezy/html2markdown/build/3.2.1.343) to prove that.
> 
> The error in your attached project occurs in [HtmlAgilityPack](http://html-agility-pack.net/). I believe this is because you have incorrectly used the latest version whereas Html2Markdown depends on [1.5.0](https://www.nuget.org/packages/Html2Markdown). NuGet should have installed that version when you installed Html2Markdown.
> 
> This project will never upgrade HtmlAgilityPack because of [zzzprojects/html-agility-pack#74](https://github.com/zzzprojects/html-agility-pack/issues/74) instead we will upgrade to [AngleSharp](https://github.com/AngleSharp/AngleSharp) in the next major version when #68 is completed.

You are absolutely right. I believe I upgraded the Html Agility Pack and this ended up breaking HTML2Markdown. When I removed both packages, and reinstalled HTML2Markdown, it came by default with Html Agility Pack 1.5.0

**Comment by makarandkeer** [comment]
I am also getting same error.
Where can I get HAP 1.5.0, as per https://www.nuget.org/packages/HtmlAgilityPack/ latest version is 1.11.23 https://www.nuget.org/packages/HtmlAgilityPack/1.11.23?

**Comment by baynezy** [comment]
NuGet has all previous versions https://www.nuget.org/packages/HtmlAgilityPack/1.5.0
